### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by GeorgeS2019** [ray440/IcuBlazor#3]
Can the project works with .NET5?
Is there a plan to support .NET5 and when?
I have problem compiling IcuBlazor.server and I see strange error message.

**Comment by ray440** [comment]
> Can the project works with .NET5?> Is there a plan to support .NET5 and when?Yes, we plan to support .NET5 shortly after the official release of .NET5.  Internally, we have a .net5 version ready to go. Let me know if you’d like to try that.> I have problem compiling IcuBlazor.server and I see strange error message.Weird. What are the error messages? - ray  From: GeorgeS2019Sent: Tuesday, November 3, 2020 5:52 AMTo: ray440/IcuBlazorCc: SubscribedSubject: [ray440/IcuBlazor] Can not compile (#3) Can the project works with .NET5?Is there a plan to support .NET5 and when?I have problem compiling IcuBlazor.server and I see strange error message.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by GeorgeS2019** [comment]
@ray440  please share a working .NET5 version. 
I have tried using the nuget, but it is meant for .NETCore3.1
I tried keeping that consistent to .NETCore3.1, still no luck. 
Please share the working internal .NET5 version.

**Comment by ray440** [comment]
OK, Just uploaded latest packages to nuget. If I may ask, How are you using IcuBlazor? What missing features would you love to see? All the best.-ray From: GeorgeS2019Sent: Tuesday, November 3, 2020 12:35 PMTo: ray440/IcuBlazorCc: Ray 440; MentionSubject: Re: [ray440/IcuBlazor] Can not compile (#3) @ray440 please share a working .NET5 version.I have tried using the nuget, but it is meant for .NETCore3.1I tried keeping that consistent to .NETCore3.1, still no luck.Please share the working internal .NET5 version.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by GeorgeS2019** [comment]
@ray440    Do u see what u paste to Github Website, instead of throw some software which does not feedback to you WHAT IS GOING WRONG with what u paste?

We need a way quickly allow people to test what u have created. 
After hours after hours, still do not work (this is NOT NORMAL, as I hardly find myself in this situation). I hope your new version will help.

**Comment by ray440** [comment]
Yikes!  I replied by email and it pasted it as full html...

**Comment by ray440** [comment]
The .NET 5.0.0-rc.2 version is released to nuget & GitHub.
